[build]
    functions = "functions"

[build.environment]
    EMAIL_HOST = "smtp.mailtrap.io"
    EMAIL_PORT = 2525
    EMAIL_SECURE = false
    EMAIL_USERNAME = "be5b4841d54c7a"
    EMAIL_PASSWORD = "020960c4a7527c"
